# Generated by Django 4.1.7 on 2023-03-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.TextField(blank=True, default='', null=True)),
                ('uniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('surname', models.TextField(blank=True, default='', null=True)),
                ('t_class', models.IntegerField(blank=True, null=True)),
                ('UID', models.TextField(default='', unique=True)),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
    ]
