# Generated by Django 4.1.7 on 2023-03-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("parentID", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, default="", null=True)),
                ("surname", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("uniqueID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, default="", null=True)),
                ("city", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, default="", null=True)),
                ("surname", models.TextField(blank=True, default="", null=True)),
                ("isAdmin", models.BooleanField(default=False)),
                (
                    "school",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.school"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, default="", null=True)),
                ("surname", models.TextField(blank=True, default="", null=True)),
                ("isPresent", models.BooleanField(default=False)),
                (
                    "parentsID",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.parent"),
                ),
                (
                    "school",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.school"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parent",
            name="school",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.school"),
        ),
    ]
